// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// w6qspi //
// ------ //

#define w6qspi_wrap_target 0
#define w6qspi_wrap 8
#define w6qspi_pio_version 0

#define w6qspi_offset_write_bits_end 3u
#define w6qspi_offset_read_bits_end 9u

static const uint16_t w6qspi_program_instructions[] = {
            //     .wrap_target
    0x6004, //  0: out    pins, 4         side 0
    0x1040, //  1: jmp    x--, 0          side 1
    0xe000, //  2: set    pins, 0         side 0
    0xe080, //  3: set    pindirs, 0      side 0
    0xf020, //  4: set    x, 0            side 1
    0x4004, //  5: in     pins, 4         side 0
    0x1045, //  6: jmp    x--, 5          side 1
    0x4004, //  7: in     pins, 4         side 0
    0x0084, //  8: jmp    y--, 4          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program w6qspi_program = {
    .instructions = w6qspi_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = w6qspi_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config w6qspi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + w6qspi_wrap_target, offset + w6qspi_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

